spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flowforge
    username: postgres
    password: postgres

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: your_super_secret_key_for_flowforge_backend_system
  expiration: 86400000

management:
  otlp:
    metrics:
      export:
        enabled: false
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
##    org.hibernate.orm.jdbc.bind: TRACE